### PR TITLE
fix: retry stdio MCP toolset when binary is unavailable at startup

### LINKED ISSUE #2410: MCP CLI tool installed after agent start is not picked up (requires restart)
### Summary

When an MCP CLI tool (stdio transport) is configured in `agent.yaml` but its binary is **not yet present** at agent startup, the agent correctly fails to use it. However, once the binary is installed/built and becomes available on PATH, the running agent **still cannot discover or use the tool** — a full restart is required.

### Reproduction

A minimal reproduction is available at: https://github.com/simonferquel/repro-docker-agent-install-mcp-after-start

The repo contains:
- `mcp-hello/` — a tiny MCP server (Go, stdio transport) with a single `hello` tool
- `build.sh` — builds the `mcp-hello` binary into `./bin/`
- `agent.yaml` — docker-agent config referencing `mcp-hello` as an MCP toolset

### Steps to Reproduce

1. Ensure the binary is **not** on PATH: `rm -rf bin/ && which mcp-hello` (should fail)
2. Start the agent: `docker agent run agent.yaml`
3. Ask the agent to use the hello tool → **fails** (expected — binary missing)
4. Build the binary in another terminal: `./build.sh`
5. Ask the agent to use the hello tool again in the still-running agent → **still fails** 🐛

### Expected Behavior

After the MCP binary becomes available on PATH, the running agent should be able to discover and use it without requiring a restart (e.g., by retrying to start the MCP server on next tool use, or by periodically checking for newly available toolsets).

### Actual Behavior

The agent continues to report the tool as unavailable even after the binary is installed. Only restarting the agent (`docker agent run agent.yaml`) resolves the issue.

### Workaround

Restart the agent after installing the MCP binary.

### Impact

This is particularly painful in development workflows where MCP tools are built and iterated on locally — every rebuild requires a full agent restart to pick up the new binary.

### PR DESCRIPTION
**Pull request by simonferquel-clanker**
When a stdio MCP toolset's binary is missing or exits immediately (before the MCP handshake completes), the toolset now leaves `started=false` and returns an error. This lets the agent runtime retry via `ensureToolSetsAreStarted()` on the next conversation turn — so tools that depend on lazily-installed binaries eventually become available.

Two failure scenarios are handled:
- **Binary not found** (`exec.ErrNotFound`, `os.ErrNotExist`): the command doesn't exist yet (e.g. installed by a Docker build step that hasn't finished).
- **Process exits immediately** (`io.EOF`): the binary exists but crashes before completing the MCP Initialize handshake.

Remote (HTTP) toolsets preserve existing behaviour: they swallow the unavailable error, mark as started, and proceed with an empty tool list.

Changes:
- Added `isStdio` field to `Toolset`, set `true` in `NewToolsetCommand()`
- New `isServerUnavailableError()` helper replaces bare `io.EOF` check; also matches `exec.ErrNotFound` and `os.ErrNotExist`
- `Start()` branches on `isStdio` for the `errServerUnavailable` case
- 5 new tests covering both stdio and remote paths, including full integration with `tools.NewStartable`

Fixes #2410

### CODE REVIEW

**Review by simonferquel — CHANGES_REQUESTED** [review]
The approach is simple but... it does not work (repro project still repro)

**Review by dgageot — DISMISSED** [review]

File: pkg/toolinstall/resolver.go [hunk 1]
```diff
@@ -16,11 +16,19 @@ import (
...
+// Path-like commands (containing a '/') are returned as-is without any
+// resolution or auto-install attempt. These refer to local binaries that
+// may not exist yet; the caller (e.g. MCP Start retry) handles availability.
+//
 // Returns the resolved command (may be the same string if found in PATH,
 // or a full path to the installed binary) and any error encountered.
 // When auto-install is disabled (globally or per-toolset), the original
 // command is returned with no error.
 func EnsureCommand(ctx context.Context, command, version string) (string, error) {
+	if strings.Contains(command, "/") {
```
Comment (simonferquel) [inline pkg/toolinstall/resolver.go]: No we can't do that

Comment (simonferquel) [reply pkg/toolinstall/resolver.go]: We need to make aqua failure retryable, just like EOF and co

**Review by simonferquel — DISMISSED** [review]
Confirmed working locally

File: pkg/tools/mcp/mcp.go [hunk 2]
```diff
@@ -159,9 +168,13 @@ func (ts *Toolset) Start(ctx context.Context) error {
 
 	if err := ts.doStart(ctx); err != nil {
 		if errors.Is(err, errServerUnavailable) {
-			// The server is unreachable but the error is non-fatal.
-			// Mark as started so the agent can proceed; tools will simply
-			// be empty. Don't spawn a watcher — there's nothing to watch.
+			if ts.isStdio {
```
Comment (rumpl) [inline pkg/tools/mcp/mcp.go]: Why do we need to know this?

Comment (simonferquel) [reply pkg/tools/mcp/mcp.go]: This is to make sure the retry logic only applies to local mcp tools. Retrying remote mcp tools might introduce performance penalty

Comment (simonferquel-clanker) [reply pkg/tools/mcp/mcp.go]: Addressed — the comment on the `isStdio` branch has been updated to capture @simonferquel's rationale: stdio (local) toolsets retry on each turn because the binary may appear later; remote toolsets keep the existing swallow-and-mark-started behaviour to avoid a performance penalty on every turn.

Comment (rumpl) [reply pkg/tools/mcp/mcp.go]: Wait what, we used to retry all the failed mcp servers.

Comment (simonferquel-clanker) [reply pkg/tools/mcp/mcp.go]: Good catch — you're right. The `isStdio` branch has been removed entirely in the latest push (commit `42e6d448`). `Start()` now propagates all errors for both stdio and remote toolsets, restoring the retry-all behaviour from your original `1e213ce1`. Thanks for the correction!

**Comment by simonferquel-clanker** [comment]
Hi @simonferquel — wanted to check in on the `isStdio` removal before the next iteration.

We investigated whether remote MCP toolsets have a background retry mechanism (watchConnection/tryRestart) that would make the `isStdio` distinction meaningful. Here's what we found:

**When `errServerUnavailable` is returned for a remote toolset (original code):**
- `watchConnection` is explicitly NOT spawned (the comment says 'Don't spawn a watcher — there's nothing to watch')
- No other background goroutine exists for this case
- `watchConnection` is a 'was connected, now dropped' mechanism — it relies on `Wait()` on a live session, which immediately returns nil if `Initialize()` never succeeded
- Result: the remote toolset is **permanently dead** with empty tools and no recovery path — same bug as stdio

So the `errServerUnavailable` swallow appears to be an oversight for both types, not an intentional design for remote.

That said, you flagged concern about removing `isStdio`. **Should we:**
a) Keep the removal — fix the retry bug for both stdio and remote (current state of the PR)
b) Restore `isStdio` — fix stdio only, leave remote behaviour as-is (with a clear comment explaining why)

Happy to go either way based on your call.

**Comment by simonferquel** [comment]
I have no strong opinion on that and would rather let @rumpl or @dgageot decide

**Comment by simonferquel-clanker** [comment]
@rumpl @dgageot — Simon is happy either way and defers to you. To summarise the choice:

**Option a) Current PR state** — `isStdio` removed, retry applies to all toolset types (stdio + remote). Investigation confirmed there is no background retry for remote toolsets when initially unavailable — the `errServerUnavailable` swallow left them permanently dead with no recovery path, same as the stdio bug we're fixing. Fixing both is consistent and simpler code.

**Option b) Restore `isStdio`** — retry for stdio only, leave remote behaviour as-is (permanently dead on startup unavailability, with a clear comment). Smaller blast radius for this PR.

The current code (option a) is CI-green, tmux-verified, and internally reviewed. Happy to switch to option b if you prefer the more conservative approach.

**Review by dgageot — APPROVED** [review]
