### PR TITLE
Fix stream cancellation in the TUI

### LINKED ISSUE #597: Cancelling a stream breaks the TUI
Canceling a response mid-stream leaves the TUI in a broken state where the "Working" and loading spinners remain active instead of also being stopped, and no further messages can be sent by the user

Screenshot of a canceled stream

Image

### PR DESCRIPTION
**Pull request by krissetto**
Fixes stream cancellation logic in the TUI by stopping and removing all spinners, allowing the user to send followup messages, and adds a message indicating to the user that the stream has been canceled

---

Screenshot

Screenshot From 2025-10-24 13-49-30

---

Closes #597

### CODE REVIEW

File: pkg/tui/components/messages/messages.go [hunk 1]
```diff
@@ -31,12 +31,15 @@ type Model interface {
...
 	AddAssistantMessage() tea.Cmd
 	AddSeparatorMessage() tea.Cmd
+	AddCancelledMessage() tea.Cmd
 	AddOrUpdateToolCall(agentName string, toolCall tools.ToolCall, toolDef tools.Tool, status types.ToolStatus) tea.Cmd
 	AddToolResult(msg *runtime.ToolCallResponseEvent, status types.ToolStatus) tea.Cmd
 	AppendToLastMessage(agentName string, messageType types.MessageType, content string) tea.Cmd
 	ScrollToBottom() tea.Cmd
 	AddShellOutputMessage(content string) tea.Cmd
 	AddSystemMessage(content string) tea.Cmd
+	RemoveSpinner()
```
Comment (rumpl) [inline pkg/tui/components/messages/messages.go]: Instead of making this public it would be nicer maybe to have a command that is sent down to all the components that tell them that the stream is cancelled, WDYT? Just asking

Comment (krissetto) [reply pkg/tui/components/messages/messages.go]: Agree, I changed this

**Review by rumpl — APPROVED** [review]
