### PR TITLE
fix(otel): align service resource schema

### LINKED ISSUE #2416: OpenTelemetry error `failed to create resource: conflicting Schema URL`
**Describe the bug**

Starting docker-agent with OpenTelemetry tracing enabled is failing with the following warning:
`msg="Failed to initialize OpenTelemetry SDK" error="failed to create resource: conflicting Schema URL: https://opentelemetry.io/schemas/1.40.0 and https://opentelemetry.io/schemas/1.37.0"`

**Version affected**

`docker-agent version v1.44.0`

**How To Reproduce**

1. Execute `docker-agent models --otel --debug`
2. Look at the file `~/.cagent/cagent.debug.log`
3. There is a `WARN` log entry with the message mentioned above

**Expectation**

- No warning
- OpenTelemetry tracing works

**Screenshots**

n/a

**OS and Terminal type**

macOS Tahoe 26.4 / iTerm2

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by pandego**
## Summary
- align the custom OTel service resource with the SDK default schema URL
- extract the resource construction into a helper and add a regression test for the schema URL

## Related issue
- Closes #2416

## Testing
- `docker run --rm -v "$PWD":/src -w /src golang:1.26 sh -lc '/usr/local/go/bin/gofmt -w cmd/root/otel.go cmd/root/otel_test.go && /usr/local/go/bin/go test ./cmd/root -run "Test(NewOTelResourceUsesCurrentSchemaURL|IsLocalhostEndpoint)" -count=1'`

### CODE REVIEW

**Comment by dgageot** [comment]
cc @derekmisler

File: cmd/root/otel.go [hunk 1]
```diff
@@ -77,6 +70,17 @@ func initOTelSDK(ctx context.Context) (err error) {
 
 // isLocalhostEndpoint reports whether the given endpoint refers to a
 // loopback address so that we can safely skip TLS.
```
Comment (derekmisler) [inline cmd/root/otel.go:72]: **typo:** `godoc` attaches a comment block to whichever declaration immediately follows it, so these comments should stay near the `isLocalhostEndpoint` function.

File: cmd/root/otel.go [hunk 2]
```diff
@@ -12,21 +12,14 @@ import (
 	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
 	"go.opentelemetry.io/otel/sdk/resource"
 	"go.opentelemetry.io/otel/sdk/trace"
-	semconv "go.opentelemetry.io/otel/semconv/v1.37.0"
+	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
```
Comment (derekmisler) [inline cmd/root/otel.go:15]: **praise (🥇):** This upgrade is completely safe. The codebase uses only three fundamental resource-level symbols (`SchemaURL`, `ServiceName`, `ServiceVersion`) that are core to every semconv release and are not part of any breaking change across `v1.38.0`, `v1.39.0`, or `v1.40.0`.

**Review by derekmisler — COMMENTED** [review]
I had just one comment regarding the placement of a comment, otherwise everything else looks good to me. I see you have a lint error, so let me know once that's fixed and I'll approve.

Thank you, @pandego!

File: cmd/root/otel.go (hunk 1 above)
Comment (pandego) [reply cmd/root/otel.go]: Thanks, good catch. I moved the comment block so it stays attached to `isLocalhostEndpoint`, and also fixed the lint issue.

Local validation run:
- `go test ./cmd/root/...`

**Comment by elgreco247** [comment]
@derekmisler Any chance you've got time for a review?

**Review by derekmisler — APPROVED** [review]
