### PR TITLE
Fix oauth with streamable mcp servers

### LINKED ISSUE #485: OAuth flow failure Prisma MCP Server
**Describe the bug**

The OAuth flow fails with Prisma

1. Create an agent with

```
#!/usr/bin/env cagent run
version: '2'

agents:
  root:
    model: anthropic/claude-3-5-sonnet-latest
    description: Prisma Expert
    instruction: You are an AI assistant with expertise in the Prisma project's documentation.
    toolsets:
      - type: mcp
        remote:
          url: https://mcp.prisma.io/mcp
          transport_type: streamable
```

2. Start running this agent with random question. The OAuth flow seems to pass through, but then subsequent requests fail with 400

### PR DESCRIPTION
**Pull request by rumpl**
req.Clone makes a shallow copy of the body so the first call would
consume the body completely, making the next call after oauth flow an
empty request, this would give us a 400 Bad Request.

Keep the body so that we can re-inject it into the original request
before re-sending with the token.

Fixes #485

### CODE REVIEW

File: pkg/tools/mcp/oauth.go [hunk 1]
```diff
@@ -336,6 +336,16 @@ type oauthTransport struct {
 }
 
 func (t *oauthTransport) RoundTrip(req *http.Request) (*http.Response, error) {
+	var bodyBytes []byte
+	if req.Body != nil && req.Body != http.NoBody {
+		var err error
+		bodyBytes, err = io.ReadAll(req.Body)
```
Comment (findleyr) [inline pkg/tools/mcp/oauth.go:342]: Hi, @jba referred me here as I'm fixing this in the MCP client implementation.

I think you need to close the body after reading it, as RoundTripper says that RoundTrip must always close the body.
