### PR TITLE
Fix speech to text on macOS

### LINKED ISSUE #1919: /speak not working - Speech-to-text is not yet supported
**Describe the bug**

when I use /speak I get an error message "Speech-to-text is not yet supported" and i can't talk to cagent anymore

**Version affected**

v1.29.0

**How To Reproduce**

Detailed steps to reproduce the behavior:

in TUI type /speak a

**Expectation**

I can talk to cagent

Image

**Screenshots**

**OS and Terminal type**

Mac + Ghostty

### PR DESCRIPTION
**Pull request by dgageot**
Fixes #1919

### CODE REVIEW

File: pkg/tui/handlers.go [hunk 1]
```diff
@@ -531,6 +531,69 @@ func (m *appModel) handleAttachFile(filePath string) (tea.Model, tea.Cmd) {
 	})
 }
 
+// --- Speech-to-text ---
```
Comment (aheritier) [inline pkg/tui/handlers.go:534]: speech to text or text to speech ?

Comment (dgageot) [reply pkg/tui/handlers.go:534]: What the code says :-)
