### PR TITLE
fix(editor): prevent thread block when attachment file is deleted

### LINKED ISSUE #1735: Deleting a referenced file during thread, block the thread.
Reference a file with @ like a simple image
make a few message with it.
Then delete the file on your disk.

Then cagent will try to load the file all the time, or keep a reference on it, and will fail to comply with any message rendering the curfrent thread useless.

WE should likely gracefully noting a file is not referenceed anymore and not block the stream

### PR DESCRIPTION
**Pull request by Pnkcaht**
## What I did

- Prevented thread blocking when an attachment file is deleted.
- Updated collectAttachments to log and skip missing files instead of breaking the render flow.
- Ensured temporary files are cleaned safely.
- Preserved non-temporary attachments when appropriate.

## Releated Issue

- Fixes #1735

### CODE REVIEW

File: pkg/tui/components/editor/editor.go [hunk 1]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
 }
 
-// AttachFile adds a file as an attachment and inserts @filepath into the editor
+// AttachFile safely adds a file as an attachment and inserts @filepath into the editor.
+// If the file does not exist or is not accessible, the reference is ignored gracefully.
 func (e *editor) AttachFile(filePath string) {
+	// Validate the file exists before attempting to attach it
+	if info, err := os.Stat(filePath); err != nil {
+		if os.IsNotExist(err) {
+			// fully qualify log package to avoid shadowing
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: don't need this comment

File: pkg/tui/components/editor/editor.go [hunk 2]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
+		} else {
+			log.Println("AttachFile skipped: cannot access file '"+filePath+"':", err)
+		}
+		return
+	} else if info.IsDir() {
+		log.Println("AttachFile skipped: '" + filePath + "' is a directory, not a file.")
+		return
+	}
+
+	// Build the placeholder reference
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: same as ☝️

File: pkg/tui/components/editor/editor.go [hunk 3]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
 	placeholder := "@" + filePath
+
+	// Add the file as an attachment
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: same as ☝️

File: pkg/tui/components/editor/editor.go [hunk 4]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
 	e.addFileAttachment(placeholder)
+
+	// Insert the placeholder into the editor textarea
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: same as ☝️

File: pkg/tui/components/editor/editor.go [hunk 5]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
 	currentValue := e.textarea.Value()
 	e.textarea.SetValue(currentValue + placeholder + " ")
+
+	// Move cursor to the end and mark user activity
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: same as ☝️

File: pkg/tui/components/editor/editor.go [hunk 6]
```diff
@@ -1286,21 +1287,45 @@ func (e *editor) InsertText(text string) {
...
 	e.textarea.MoveToEnd()
 	e.userTyped = true
+
+	// Update any UI indicators or banners
 	e.updateAttachmentBanner()
 }
 
-// tryAddFileRef checks if word is a valid @filepath and adds it as attachment.
-// Called when cursor leaves a word to detect manually-typed file references.
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go:1288]: lets leave this part as well as its describes the reason it gets called and when

File: pkg/tui/components/editor/editor.go [hunk 7]
```diff
@@ -1310,11 +1335,29 @@ func (e *editor) tryAddFileRef(word string) {
 		return
 	}
 
-	path := word[1:] // strip @
-	if !strings.ContainsAny(path, "/.") {
-		return // not a path-like reference (e.g., @username)
+	filePath := word[1:] // remove '@'
+
+	// Must look like a path (contains '/' or '.')
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: can be removed

File: pkg/tui/components/editor/editor.go [hunk 8]
```diff
@@ -1354,46 +1397,70 @@ func (e *editor) addFileAttachment(placeholder string) {
...
-// collectAttachments returns structured attachments for all items referenced in
-// content. For paste attachments the content is read into memory (the backing
-// temp file is removed). For file-reference attachments the path is preserved
-// so the consumer can read and classify the file (e.g. detect MIME type).
-// Unreferenced attachments are cleaned up.
-func (e *editor) collectAttachments(content string) []messages.Attachment {
+// collectAttachments returns a map of placeholder -> file content
+// for all attachments referenced in the provided content.
+func (e *editor) collectAttachments(content string) map[string]string {
+	// Fast path: nothing to process
```
Comment (krissetto) [inline pkg/tui/components/editor/editor.go]: no need

**Review by krissetto — DISMISSED** [review]
same with other comments, sorry ;) if the code is self explanatory, comments are extra things to maintain

**Comment by ghost** [comment]
Done, I totally agree :) @krissetto

**Review by trungutt — APPROVED** [review]
