### PR TITLE
Fix/tui aggregated token cost

### LINKED ISSUE #504: Token tracking when using subagents
At the moment the token tracking code in the TUI only seems to consider the currently active agent/session. 

This means that the values displayed in the TUI change when an agent delegates a task to a sub-agent or a sub-agent finishes its task and returns control to it's parent, not giving the user a precise indication of the tokens actually used when running an agent team

It'd be nice to have an overall view of total tokens consumed by the full agent team, and also a way to see the consumption and cost per individual session (which would mean per sub-agent as well).

### PR DESCRIPTION
**Pull request by riturajFi**
**Multi-session token tracking in runtime + sidebar**

---

### **Overview**

fixes #504 

Expands runtime token-usage events to include session IDs and both self vs. inclusive snapshots, allowing downstream consumers to correlate root and child sessions.

The runtime now:

* Aggregates self/child token totals.
* Emits refreshed snapshots after compaction and task transfers.

The sidebar is modernized to:

* Present “Total usage” with comma separators.
* Add a sortable session breakdown.
* Highlight the active agent’s self-spend.

---

### **Implementation Highlights**

* **pkg/runtime/event.go**, **pkg/session/session.go**
  Introduce richer `TokenUsageEvent` payloads and per-session `self` fields, distinguishing the emitting agent’s contribution from inherited child totals.

* **pkg/runtime/runtime.go**
  Calculates self vs. inclusive snapshots, merges child session usage, logs each provider chunk to `token_usage_chunks.log`, and re-emits `TokenUsage` events whenever compaction or transfers change totals.

* **pkg/tui/components/sidebar/sidebar.go**
  Replaces the single `Usage` pointer with a `usageState` map keyed by session ID. Formats totals using `humanize.Comma`, and renders a **“SESSION BREAKDOWN”** section showing root-exclusive usage plus every child session (sorted, with the active session highlighted).

* **pkg/tui/page/chat/chat.go**
  Passes the full `TokenUsageEvent` to the sidebar.

* **pkg/runtime/runtime_test.go**
  Adds snapshot helpers so expectations include the richer event payloads.

---

### **Testing**

```bash
task test
```

---

### **Screenshots / Recordings**

image

### CODE REVIEW

**Comment by riturajFi** [comment]
@krissetto — kindly take a look at this PR when you have a moment. I’d really appreciate your feedback!

I closed the previous PR since the approach there turned out to be overly complex and didn’t rebase cleanly with the updated main branch.

In this version, I’ve simplified the implementation by introducing dedicated fields for each session to track separate self and child token counts, which are then aggregated for display.

I’ve tested it with:

A root agent having multiple subagents.

Subagents that themselves have nested subagents.

There’s also a temporary logging system included to help with verification — I’ll remove it once the changes are approved for merge.

**Comment by rumpl** [comment]
For logging you can simply use `slog.Debug`, this will write the logs to ~/.cagent/cagent.debug.log`

File: pkg/tui/page/chat/chat.go [hunk 1]
```diff
@@ -249,7 +249,7 @@ func (p *chatPage) Update(msg tea.Msg) (layout.Model, tea.Cmd) {
 		}
 		return p, cmd
 	case *runtime.TokenUsageEvent:
-		p.sidebar.SetTokenUsage(msg.Usage)
+		p.sidebar.SetTokenUsage(msg) // forward full event so sidebar can track per-session usage
```
Comment (rumpl) [inline pkg/tui/page/chat/chat.go]: Please remove this log

**Comment by riturajFi** [comment]
> For logging you can simply use `slog.Debug`, this will write the logs to ~/.cagent/cagent.debug.log`

Hi @rumpl @krissetto  , removed the logging. Can you please verify the solution and if some changes need to be done?

File: pkg/tui/components/sidebar/sidebar.go [hunk 2]
```diff
@@ -192,18 +245,49 @@ func (m *model) workingIndicator() string {
...
-	totalTokensText := styles.SubtleStyle.Render(fmt.Sprintf("(%s)", formatTokenCount(totalTokens)))
-	costText := styles.MutedStyle.Render(fmt.Sprintf("$%.2f", m.usage.Cost))
+	var builder strings.Builder                                   // assemble multiline output
+	builder.WriteString(styles.SubtleStyle.Render("TOTAL USAGE")) // heading for total usage
+	if label != "" {                                              // append contextual label when available
+		builder.WriteString(fmt.Sprintf(" (%s)", label)) // show whether totals are team/session scoped
+	}
+	builder.WriteString(fmt.Sprintf("\n  Tokens: %s | Cost: $%.2f\n", formatTokenCount(totalTokens), totals.Cost)) // display totals line
+	builder.WriteString("--------------------------------\n")                                                      // visual separator
+	builder.WriteString(styles.SubtleStyle.Render("SESSION BREAKDOWN"))                                            // heading for per-session details
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: nit: Let's use `Agent breakdown` (not all caps is a bit nicer imho) instead as its more representative. each time an agent delegates to a subagent, a new session is created. This can happen more than once

File: pkg/tui/components/sidebar/sidebar.go [hunk 3]
```diff
@@ -192,18 +245,49 @@ func (m *model) workingIndicator() string {
...
+
+func (m *model) tokenUsageDetails() string { // renders aggregate usage summary line + breakdown
+	label, totals := m.renderTotals()                       // get friendly label plus computed totals
+	totalTokens := totals.InputTokens + totals.OutputTokens // sum user + assistant tokens for display
+
+	// var usagePercent float64
+	// if totals.ContextLimit > 0 {
+	// 	usagePercent = (float64(totals.ContextLength) / float64(totals.ContextLimit)) * 100
+	// }
+	// percentageText := styles.MutedStyle.Render(fmt.Sprintf("%.0f%%", usagePercent))
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: nit: this commented out code can be removed when dealing with multiple agents, but if there's only one it might be good to keep the percentage displayed

File: pkg/tui/components/sidebar/sidebar.go [hunk 4]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+	target.Cost -= prev.Cost
+}
+
+func (m *model) renderTotals() (string, *runtime.Usage) { // resolves label + totals for display
+	totals := m.computeTeamTotals() // compute aggregate usage first
+	if totals == nil {              // ensure downstream code always receives a struct
+		totals = &runtime.Usage{} // fall back to zero snapshot
+	}
+
+	label := "Team Total" // totals always represent team-wide cumulative usage
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: This is unnecessary

File: pkg/tui/components/sidebar/sidebar.go [hunk 5]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+
+	return label, totals // return computed label with totals
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: we can get rid of the comments on each line and only comment the function itself (on top of the func like `// renderTotals resolves label + totals for display`, so it appears as a go doc and devs can read it by hovering on the func name in their ides).

File: pkg/tui/components/sidebar/sidebar.go [hunk 6]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+}
+
+func (m *model) computeTeamTotals() *runtime.Usage { // derives aggregate totals for the team line
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: this comment should also be on top of the func definition in the godoc format

File: pkg/tui/components/sidebar/sidebar.go [hunk 7]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+		if agent.usage.ContextLimit > totals.ContextLimit {
+			totals.ContextLimit = agent.usage.ContextLimit
+		}
+		totals.Cost += agent.usage.Cost
+	}
+
+	return &totals
+}
+
+func (m *model) sessionBreakdownLines() []string { // renders per-agent self usage rows
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions

File: pkg/tui/components/sidebar/sidebar.go [hunk 8]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+		}
+	}
+
+	if len(lines) == 0 {
+		return nil
+	}
+	return lines
+}
+
+func (m *model) rootSessionBlock() string { // formats root agent entry with aggregated usage
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions

File: pkg/tui/components/sidebar/sidebar.go [hunk 9]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+	}
+
+	name := m.usageState.rootAgentName
+	if name == "" {
+		name = "Root"
+	}
+	return formatSessionBlock(name, rootUsage, m.usageState.activeAgent == name)
+}
+
+func formatSessionBlock(agentName string, usage *runtime.Usage, isActive bool) string { // helper to render a single block
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions

File: pkg/tui/components/sidebar/sidebar.go [hunk 10]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
 func (m *model) SetMode(mode Mode) {
 	m.mode = mode
 }
+
+func cloneUsage(u *runtime.Usage) *runtime.Usage { // helper to copy runtime usage structs safely
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions

File: pkg/tui/components/sidebar/sidebar.go [hunk 11]
```diff
@@ -222,3 +306,157 @@ func (m *model) GetSize() (width, height int) {
...
+	if u == nil { // avoid panics on nil usage snapshots
+		return nil // nothing to clone when nil
+	}
+	clone := *u   // copy by value to detach from original pointer
+	return &clone // return pointer to independent copy
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: these comments can be removed

File: pkg/tui/components/sidebar/sidebar.go [hunk 12]
```diff
@@ -192,18 +245,49 @@ func (m *model) workingIndicator() string {
...
+	if label != "" {
+		parts = append(parts, label)
 	}
+	parts = append(parts, fmt.Sprintf("Tokens: %s", totalTokens))
+	parts = append(parts, fmt.Sprintf("Cost: %s", cost))
+
+	return styles.SubtleStyle.Render(strings.Join(parts, " | "))
+}
+
+func (m *model) tokenUsageDetails() string { // renders aggregate usage summary line + breakdown
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions. also most all of the line-by-line comments in here can be removed, the code should speak for itself wherever possible :)

File: pkg/tui/components/sidebar/sidebar.go [hunk 13]
```diff
@@ -192,18 +245,49 @@ func (m *model) workingIndicator() string {
 	return ""
 }
 
-func (m *model) tokenUsage() string {
-	totalTokens := m.usage.InputTokens + m.usage.OutputTokens
-	var usagePercent float64
-	if m.usage.ContextLimit > 0 {
-		usagePercent = (float64(m.usage.ContextLength) / float64(m.usage.ContextLimit)) * 100
+func (m *model) tokenUsageSummary() string { // condensed single-line usage view for horizontal layout
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions

File: pkg/tui/components/sidebar/sidebar.go [hunk 14]
```diff
@@ -24,47 +25,103 @@ const (
...
 	}
 }
 
 func (m *model) Init() tea.Cmd {
 	return nil
 }
 
-func (m *model) SetTokenUsage(usage *runtime.Usage) {
-	m.usage = usage
+func (m *model) SetTokenUsage(event *runtime.TokenUsageEvent) { // updates usage state from runtime events
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: follow godoc conventions, and remove unnecessary line-by-line comments

File: pkg/tui/components/sidebar/sidebar.go [hunk 15]
```diff
@@ -24,47 +25,103 @@ const (
...
+		height: 24, // default height matches initial layout
+		usageState: usageState{ // initialize usage tracking containers
+			sessionTotals: make(map[string]*runtime.Usage),
+			sessionAgents: make(map[string]string),
+			agents:        make([]*agentUsage, 0),
+			agentIndex:    make(map[string]int),
+		},
+		todoComp:     todo.NewComponent(),                           // instantiate todo component
+		spinner:      spinner.New(spinner.WithSpinner(spinner.Dot)), // configure spinner visuals
+		sessionTitle: "New session",                                 // initial placeholder title
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: no need for these comments

File: pkg/tui/components/sidebar/sidebar.go [hunk 16]
```diff
@@ -24,47 +25,103 @@ const (
...
+}
+
+type usageState struct { // holds aggregated token usage snapshots grouped by agent
+	sessionTotals map[string]*runtime.Usage // latest snapshot per session
+	sessionAgents map[string]string         // sessionID -> agent name
+	agents        []*agentUsage             // ordered list of agent aggregates
+	agentIndex    map[string]int            // quick lookup for agent position
+	rootInclusive *runtime.Usage            // inclusive usage snapshot emitted by root (fallback)
+	rootAgentName string                    // resolved root agent name for comparisons
+	activeAgent   string                    // currently active agent for highlighting
```
Comment (krissetto) [inline pkg/tui/components/sidebar/sidebar.go]: no need for these comments

**Review by krissetto — COMMENTED** [review]
Thanks for working on this @riturajFi! I left a bunch of little comments, mostly nitpicks though.

One thing, i think we could streamline the sidebar UI when no subagents are configured in a team.

Also, have a look [here](https://go.dev/blog/godoc) for best practices when it comes to documenting go code, for the most part we follow those recommendations when leaving comments etc

File: pkg/tui/components/sidebar/sidebar.go (hunk 3 above)
Comment (riturajFi) [reply pkg/tui/components/sidebar/sidebar.go]: on it @krissetto

**Comment by riturajFi** [comment]
@krissetto I fixed the issues raised by you. Kindly review

**Comment by riturajFi** [comment]
Hi @rumpl  @krissetto @dgageot Would love your review of this PR! Exited to move to the next issue in the core codebase

**Comment by krissetto** [comment]
Hey @riturajFi i'm testing this out again. Could you please fix the linter errors so the CI is green? There is some unused code and some formatting issues. Also needs a rebase, sorry for that.

**Comment by riturajFi** [comment]
Hi @krissetto i shall fix everything in the next 2 hours or so. Currently dont have access to my computer 🙃🙃

**Comment by krissetto** [comment]
@riturajFi not a problem, i'll leave some comments as i test things out in the meantime. Also, could you squash the commits down when you get a chance?

**Comment by krissetto** [comment]
@riturajFi First of all, I love the enthusiasm you have in wanting to contribute to this project :heart: 

To try and guide you in the right direction to get this feature merged, i made a quick example of what i was thinking about that you can find here: https://github.com/krissetto/cagent/tree/tui-usage

It would be ideal if we could get this feature in with minimal changes to the actual runtime, focusing instead on the TUI side of things. Smaller changes are easier to review for us and will be faster to merge, then if there are followup issues we can deal with those separately :smile: 

Please have a look at the ideas in my branch (compare them directly to main), give it a try locally, and feel free to steal the code and bring it in here or open a separate PR if it makes things easier for you

Let me know what you think!

**Comment by riturajFi** [comment]
Oh...i thought you guys wanted to solve it in the backend too as any future consumer would directly have token count access.😅 if just handling things in the frontend is fine then i shall do it right away 🫡

**Comment by krissetto** [comment]
@riturajFi go for it! frontend only is more than enough right now, a consumer can always access the data from the sessions

**Comment by riturajFi** [comment]
Thanks @krissetto for the greenlight. I shall make the changes in some hours. Kindly find time to take a look.

**Comment by riturajFi** [comment]
Hi @krissetto changed the entire logic to the frontend. The changes - 

basically went through your solution and implemented it here. Thanks for your help!

**Comment by krissetto** [comment]
@riturajFi  i gave this a quick test, lookin good! One thing before merging: could you squash your changes into a single commit? Thanks!

**Comment by riturajFi** [comment]
@krissetto done

**Comment by rumpl** [comment]
Just tested this, we can merge once the CI is green, there are tweaks we can do later, mostly UX things.

Thank you @riturajFi for working on this and for your patience <3
