### PR TITLE
tui(edit_file): skip diff rendering on tool failure

### LINKED ISSUE #1366: When edit failed, scrollbar is badly drawn
Had a `Edit 1 failed: old text not found` and before the scroll bar was out of bounds

Image

### PR DESCRIPTION
**Pull request by Pnkcaht**
## What I did

Adjusted the `edit_file` TUI rendering logic to **skip diff rendering when the tool execution fails**.

When an edit fails (e.g. *old text not found*), the tool does not produce a valid file state. Attempting to render a diff in this scenario led to inconsistent layout calculations and caused the editor scrollbar to go out of bounds.

This change ensures that, on failure, the TUI renders only the formatted error message and avoids invalid diff rendering.

## Related issue

Fixes #1366

## Notes

- Skips diff rendering when the `edit_file` tool returns an error  
- Prevents invalid layout and viewport calculations in the editor  
- Avoids scrollbar overflow after failed edits  
- Keeps existing behavior unchanged for successful edits  
- Purely a TUI rendering fix (no tool or API behavior changes)

### Before

When an `edit_file` operation failed (e.g. *old text not found*):

- The TUI still attempted to render a diff  
- Diff rendering was based on an invalid file state  
- Layout calculations became inconsistent  
- The editor scrollbar could go out of bounds  
- The UI appeared broken after the failed edit  

### After

When an `edit_file` operation fails:

- Diff rendering is skipped entirely  
- Only the formatted error message is shown  
- Layout and viewport calculations remain consistent  
- The editor remains usable and visually stable  
- Successful edits continue to render diffs as before

### CODE REVIEW

**Comment by ghost** [comment]
### New changes
I adjusted the code to fix the Lint and Test errors on GitHub. A "Resolve conflict" message also appeared in the editfile.go file, which I've already accepted and committed.

File: pkg/tui/components/tool/editfile/editfile.go [hunk 1]
```diff
@@ -15,37 +15,64 @@ import (
...
+	// Parse tool arguments to extract the file path for display.
 	var args builtin.EditFileArgs
 	if err := json.Unmarshal([]byte(msg.ToolCall.Function.Arguments), &args); err != nil {
+		// If arguments cannot be parsed, fail silently to avoid breaking the TUI.
 		return ""
 	}
 
-	// Check for friendly description first
-	var content string
-	if header, ok := toolcommon.RenderFriendlyHeader(msg, s); ok {
```
Comment (krissetto) [inline pkg/tui/components/tool/editfile/editfile.go:30]: Watch out, we recently merged a new feature that allows the agent to describe what its doing with a tool call, and that's what shows up in this `FriendlyHeader` 

Here's the PR you can reference with more context: https://github.com/docker/cagent/pull/1432

Comment (ghost) [reply pkg/tui/components/tool/editfile/editfile.go:30]: Gotcha, I'll take a look at it and get back to you with the push, thanks

**Comment by ghost** [comment]
### New changes 

I performed the rebase and made the requested change based on reference #1432.
Below is a diagram briefly explaining the old process, which became incorrect after the changes in the aforementioned reference, and the new process that correctly handles the Friendly header. @krissetto 

image

**Comment by krissetto** [comment]
The diff doesn't render on invalid diffs, nice! 

There are some small issues with the rendering of tool errors/rejections we need to fix before merging though.  

We should:
- keep some spacing between the tool badge and the error/rejection text;
- keep the same font styling so it appears consistent with the name of the tool (the "Edit README.md" in the image)
- make sure to truncate the rejection/error text it if its longer than the available space on the line. Right now it word-wraps off the edge if the terminal is not wide enough

image

**Comment by ghost** [comment]
## What was changed
@krissetto 
This update improves how the `edit_file` tool behaves and renders output when an edit fails.

### Error handling & rendering
- Skip diff rendering when the tool execution fails, as rendering diffs on failed edits can break layout and scroll calculations.
- Render tool errors/rejections as a **single-line message** directly below the tool header.
- Keep **consistent spacing and styling** with the tool header (`Edit <file>`), so errors visually match other tool messages.
- Truncate long error messages to the available terminal width to avoid wrapping or overflowing on narrow terminals.

### Why
- Failed edits do not produce meaningful diffs and attempting to render them can cause UI issues.
- Consistent styling and truncation improve readability and keep the TUI layout stable across different terminal sizes.

**Comment by krissetto** [comment]
@Pnkcaht Look at the diff edit error at the top on the terminal, we should style it to be consistent with the other tool errors you can see towards the bottom

image

**Comment by ghost** [comment]
> @Pnkcaht Look at the diff edit error at the top on the terminal, we should style it to be consistent with the other tool errors you can see towards the bottom

Okay, I'll just finish a pull request for an issue I was working on and resolve this, thank you :)

**Comment by ghost** [comment]
@krissetto  I updated the rendering of the file editing failure to use ToolErrorMessageStyle, matching the error style used by other tools

**Comment by krissetto** [comment]
for consistency, the tool name needs fixing because it still has the wrong style compared to the screenshot above, and the error/rejection message has to be on the same line (truncated if too long for the current terminal width)
image

**Comment by ghost** [comment]
We now display `edit_file` errors using the same error header layout as other tools: error icon, tool name in error style, and a single-line message truncated to the terminal width. Diff rendering is skipped entirely on failure. @krissetto I was unable to test this locally due to the lack of a running mechanism.

File: pkg/tui/components/tool/editfile/editfile.go [hunk 2]
```diff
@@ -15,37 +15,88 @@ import (
...
+			return ""
+		}
+
+		// Render everything on a single line:
+		// - error icon
+		// - tool name in error style
+		// - rejection/error message
+		line := fmt.Sprintf(
+			"%s%s %s",
+			styles.ToolErrorIcon.Render("✖ "),
```
Comment (krissetto) [inline pkg/tui/components/tool/editfile/editfile.go]: @Pnkcaht i know i'm tedious, but we're close! :sweat_smile: 

Take a look at `.../toolcommon/common.go`

The `x` char used here isn't the same, we use `✗` elsewhere


image

Comment (ghost) [reply pkg/tui/components/tool/editfile/editfile.go]: No problem, relax, I agree 😆

**Comment by ghost** [comment]
@krissetto I fixed the X 👍🏻

**Review by krissetto — APPROVED** [review]
