### PR TITLE
fix: make HTTP 429 retryable when no fallback model, respect Retry-After header

### LINKED ISSUE #2095: Handle HTTP 429 and 500 errors as retryable in model provider
## Problem

The docker agent model provider currently does not treat HTTP 429 (Too Many Requests) or HTTP 500 (Internal Server Error) responses as retryable errors, causing requests to fail immediately when these transient conditions occur.

### HTTP 429 (Too Many Requests)
- Treat as a retryable error **only when there is no fallback model configured**
- Respect any `Retry-After` header sent by the server in the response to determine how long to wait before retrying
- If no `Retry-After` header is present, use the existing backoff logic

### HTTP 500 (Internal Server Error)
- Treat as a retryable error unconditionally
- Use the same backoff logic as other existing retryable errors (no `Retry-After` support needed)

## Context

Discovered from agentic platform work where rate-limiting and transient server errors cause unnecessary failures that could be recovered automatically.

### PR DESCRIPTION
**Pull request by simonferquel-clanker**
## Summary

Fixes #2095

When the model provider returns **HTTP 429 (Too Many Requests)**:
- **With fallback models configured** → skip to the next fallback immediately (existing behaviour preserved)
- **Without fallback models** → retry the same model, honouring the `Retry-After` response header (capped at 60 s), falling back to exponential backoff when the header is absent

**HTTP 500** was already retryable via `IsRetryableStatusCode` — no change needed.

### `pkg/modelerrors/modelerrors.go`
- `ExtractRetryAfter(err error) time.Duration` — extracts `Retry-After` from `*anthropic.Error` and `*openai.Error` (both expose `*http.Response`); supports integer-seconds and HTTP-date formats
- `parseRetryAfterHeader(value string) time.Duration` — parses the header per RFC 7231 §7.1.3
- `ClassifyModelError(err error) (retryable, rateLimited bool, retryAfter time.Duration)` — unified classifier used by the retry loop; existing `IsRetryableModelError` / `IsRetryableStatusCode` unchanged for backward compatibility
- `MaxRetryAfterWait` constant (60 s cap) to prevent a misbehaving server from blocking the agent indefinitely

### `pkg/runtime/fallback.go`
- Replaced both `IsRetryableModelError` call sites with `ClassifyModelError`
- Extracted `handleModelError` helper method to avoid duplicating classification logic across stream-creation and stream-handling error paths
- Added `retryDecision` type (`Continue` / `Break` / `Return`) for clarity

### Tests
- `pkg/modelerrors/modelerrors_test.go`: `TestClassifyModelError`, `TestExtractRetryAfter`, `TestParseRetryAfterHeader`
- `pkg/runtime/fallback_test.go`: `TestFallback429WithFallbacksSkipsToNextModel`, `TestFallback429WithoutFallbacksRetriesSameModel`, `TestFallback429WithoutFallbacksExhaustsRetries`, `TestFallback500RetryableWithBackoff`

## Note on HTTP 500

HTTP 500 was already handled as retryable by `IsRetryableStatusCode(500) == true` before this PR. The requirement is satisfied by the existing code; this PR adds an explicit test (`TestFallback500RetryableWithBackoff`) to document and protect that behaviour.

### CODE REVIEW

File: pkg/modelerrors/modelerrors.go [hunk 1]
```diff
@@ -27,6 +30,14 @@ const (
 	backoffJitter    = 0.1
 )
 
+// maxRetryAfterWait caps how long we'll honor a Retry-After header to prevent
+// a misbehaving server from blocking the agent for an unreasonable amount of time.
+const maxRetryAfterWait = 60 * time.Second
```
Comment (rumpl) [inline pkg/modelerrors/modelerrors.go]: This is only used a few lines below, we can merge these two

File: pkg/modelerrors/modelerrors.go [hunk 2]
```diff
@@ -296,6 +307,92 @@ func IsRetryableModelError(err error) bool {
 	return false
 }
 
+// ExtractRetryAfter extracts the Retry-After duration from an HTTP error response.
+// Works with Anthropic and OpenAI SDK error types that expose *http.Response.
+// Returns 0 if no Retry-After header is present or the error type is unsupported.
+func ExtractRetryAfter(err error) time.Duration {
```
Comment (rumpl) [inline pkg/modelerrors/modelerrors.go]: This logic should somehow be implemented in each provider, not here IMO

File: pkg/model/provider/openai/retry.go [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+	"net/http"
+	"strconv"
+	"time"
+
+	openaisdk "github.com/openai/openai-go/v3"
+)
+
+// ExtractRetryAfter extracts the Retry-After wait duration from an OpenAI API error.
+// Returns 0 if the error is not an *openai.Error, has no response, or has no Retry-After header.
+func ExtractRetryAfter(err error) time.Duration {
```
Comment (simonferquel) [inline pkg/model/provider/openai/retry.go]: This seems to be the same exact same as the anthropic implementation.
I like the idea of having each provider customize the retry after extraction, but I'd also like to avoid code duplication

File: pkg/model/provider/retry.go [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+	"github.com/docker/docker-agent/pkg/model/provider/anthropic"
+	"github.com/docker/docker-agent/pkg/model/provider/openai"
+)
+
+// ExtractRetryAfter extracts the Retry-After wait duration from a provider error.
+// It delegates to each provider package to keep provider-specific SDK knowledge
+// local to each provider.
+// Returns 0 if no Retry-After header is found or the error type is unsupported.
+func ExtractRetryAfter(err error) time.Duration {
```
Comment (rumpl) [inline pkg/model/provider/retry.go]: We shouldn't need this. Providers could return a typed error that contains everything we need so the check would become (in fallbac) a `errors.As` or whatever

**Comment by simonferquel** [comment]
I like the new approach, letting @rumpl to take the final decision

**Comment by simonferquel** [comment]
/review

triggering docker agent for good measure
